### ISSUE TITLE
Naming of image files when the file name is an url-parameter of a script

### ISSUE THREAD

**Issue by vommie** [alexopus/SaveImageRouter#1]
Hello,

SaveImageRouter seems to have problems with naming image files if the img-src is pointed to a script like php by a get parameter.

Example:
`<img src="http://192.168.1.120/tt-rss/public.php?op=cached_url&hash=4811b1a39d218ff650bc4d9670450c671cd895c4.png">`

If you try to save this image, the file name will be "public.php" if no suffix or prefix is set in the rule. I know this is a quite special but not so uncommon case in the web. It would be great if you're able to implement a handling or exception for this type of case

I found out at the duckduckgo image search results page there's the same case:
//images.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.niffylux.com%2Fcomponents%2Fcom_virtuemart%2Fshop_image%2Fproduct%2FMer__3_4adcbad66ec11.jpg&f=1

In that example the image file name will just be "duckduckgo.com_", without any extension. 

Thanks and best regards!
- Marcus

**Comment by alexopus** [comment]
Thanks for the report. I will investigate it, should be possible to fix, at least for the duckduckgo case.

**Comment by alexopus** [comment]
This should now be fixed in version 0.2.12.
Feel free to re-open if the issue persists with that version.
