### ISSUE TITLE
File Renaming Counter stops at 100

### ISSUE THREAD

**Issue by vommie** [alexopus/SaveImageRouter#2]
Hello,

if you activate the renaming option for file names which already exists, SIR appends a counter to the file name like (1), (2), (3) ... and so on. But this counter seems to be capped at 100. After the 100, a "Save file as ..."-dialog appears and you have to rename the file by yourself. Is it possible for you to increase / uncap that counter?

Chromium Version 61.0.3163.100 (Offical Build) (64-Bit), Windows 7 (x64)

**Comment by alexopus** [comment]
This seems to be a feature in Chrome:
https://bugs.chromium.org/p/chromium/issues/detail?id=437362

You can workaround it by activating the renaming feature in SIR, and using a timestamp as prefix or suffix.
